### ISSUE TITLE
Deprecating sandbox / apaleo.io [May 4th, 2019]

### ISSUE THREAD

**Issue by andreastubbe** [apaleo/announcements#3]
On May the 4th 2019, we will shut down our sandbox environment (apaleo.io). Because sandboxes are for babies.

**Am I affected?** If your test account is on apaleo.io, or if you are using single-hotel credentials for an account on apaleo.io.

**What to do?** Be sure to migrate all your URLs to apaleo.com. It should be pretty straight forward, just search and replace. The functionality is exactly the same, only the URL differs. If you need a new test account or new test/dev credentials, follow the steps in the updated [getting started guide](https://apaleo.com/getting-started-with-apaleo-apis/), or contact us.

If you still use the single-hotel-credentials, might be a good time to switch to the way awesomer [apaleo connect flow](https://apaleo.com/connect-your-app-with-oauth-2-0/).

May the force be with you.

**Comment by lukeclifton** [comment]
Hey @andreastubbe. We currently use `sandbox` environment for local development. Do you suggest we switch to using `staging` environment for development instead now?

**Comment by pgrm** [comment]
sandbox is gone
