### ISSUE TITLE
[Jan 10, 2020] Deprecate from and to in invoiceList & VAT report filters 

### ISSUE THREAD

**Issue by andreastubbe** [apaleo/announcements#38]
We introduced a new field for 
`GET /reports/v1/reports/company-invoices-vat` and `GET /finance/v1/invoices`, `dateFilter`.

Use this, instead of the `from` and `to` fields. Until the old fields are removed, you can specify both values. Note that dateFilter takes precedence.

# How to specify dates
In the filter, you can provide an array of string expressions which all need to apply.
Each expression has the form of 'OPERATION_VALUE' where VALUE needs to be a date, and OPERATION can be:
- `eq` for equals
- `neq` for not equals
- `lt` for less than
- `gt` for greater than
- `lte` for less than or equals
- `gte` for greater than or equals

# Examples:
`eq_2019-10-10` - the date is October 10th, 2019
`lte_2019-12-31` - the date is before (or equals) December 31st 2019.

# Migration
If you want to keep your filters exactly as they were, pass the following:
`[lt_{your old value for 'to'}, gte_{your old value for 'from'}]`

If you filtered to get exactly one day, you can simplify your query:
`[eq_{the day}]`

**Comment by bennetone** [comment]
already deprecated
