### ISSUE TITLE
Changes in the folio-actions API [May 1st, 2019]

### ISSUE THREAD

**Issue by nfidirko** [apaleo/announcements#7]
We are deprecating the `GrossAmount` field in favor of the `Amount` field for allowances.
On **May 1st, 2019**, the `GrossAmount` field will be removed for the following endpoints:

- POST /finance/v1/folio-actions/{folioId}/allowances
- POST /finance/v1/folio-actions/{folioId}/charges/{chargeId}/allowances

Please use the `Amount` field instead.

**Comment by ServicePlusGmbH** [comment]
while connect flow we received following character in the access token 

	ࠁ
