### ISSUE TITLE
Time Slice Definitions API changes [August 23th, 2021]

### ISSUE THREAD

**Issue by coherent-edkarhuber** [apaleo/announcements#89]
We're introducing a new set of the time-slice-definitions APIs in the Settings API, allowing you to manage time slice definitions in more intuitive way

The new endpoints are:
 - ```POST /settings/v1/properties/{propertyId}/time-slice-definitions```
 - ```PATCH /settings/v1/properties/{propertyId}/time-slice-definitions/{id}```
 - ```DELETE /settings/v1/properties/{propertyId}/time-slice-definitions/{id}```

-------
**DEPRECATION**

In addition to the changes above, we will stop support ```PATCH /settings/v1/properties/{propertyId}/time-slice-definitions``` API on **October,1st 2021**. 
Please ensure that your apps are aware of this deprecation.

**Comment by edkarhuber** [comment]
Closed since the API changes have been applied
