### ISSUE TITLE
Deprecation of Webhook health checks

### ISSUE THREAD

**Issue by ozonni** [apaleo/announcements#99]
We are deprecating webhook health checks. Starting from **July 1st 2022** we will stop delivering health check events every two minutes. 

Health check will be now sent only once when the subscription gets created to validate that your HTTP endpoint exists. 

To monitor the availability of Webhook service you can subscribe to our [Status Page](https://status.apaleo.com/).

**Comment by edkarhuber** [comment]
Close the announcement: we stopped delivering webhook health check events.
Health check will be now sent only once when the subscription gets created to validate that your HTTP endpoint exists.
